---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rabbitmq
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./addons/base/rabbitmq-soarian
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system