---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./addons/base/weave-gitops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system